version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: environment/dockerfiles/app.dockerfile
      args:
        xdebug: 'true'
        tinker: 'true'
    user: '1000:1000'
    volumes:
      - './:/var/www:delegated'
    env_file:
      - environment/.docker.env
  web:
    build:
      context: ./
      dockerfile: environment/dockerfiles/web.dockerfile
    environment:
      - FAST_CGI_HOST=app
    volumes:
      - './:/var/www:delegated'
    ports:
      - '8080:80'
  database:
    image: 'mysql:5.7'
    volumes:
      - 'dbdata:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
  redis:
    image: 'redis'
    ports:
      - 6379:6379
    expose:
      - 6379
volumes:
  dbdata: null
